matrix:
  include:
    # OSX
    - os: osx
      install:
      - brew uninstall node
      - brew install ansible
      script:
      - mv test-ansible.cfg ansible.cfg
      - ansible-playbook -i "localhost," -c local test.yml -vvvv
      - cd tests/solidarity
      - npm install
      - npx solidarity

    # Linux
