matrix:
  include:
    # OSX
    - os: osx
      install:
      - brew install ansible
      script:
      - cp test-ansible.cfg ../ansible.cfg
      - cp test.yml ../test.yml
      - cd ../
      - mv ansible-role-react-native react-native
      - ansible-playbook -i 'localhost,' -c local test.yml -vvvv
      - cd react-native/tests/solidarity && npm install && npx solidarity

    # Linux
