matrix:
  include:
    # OSX
    - os: osx
      install:
      - brew install ansible
      script:
      - mv test-ansible.cfg ../ansible.cfg
      - mv test.yml ../test.yml
      - cd ../
      - ls -la
      - ansible-playbook -i 'localhost,' -c local test.yml -vvvv

    # Linux
