---
- name: Install homebrew
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"' 
  args:
    creates: /usr/local/bin/brew

- name: Update homebrew
  homebrew:
    state: latest
    update_homebrew: yes

- name: Enable homebrew binaries
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH="/usr/local/bin:$PATH"'

- name: Install node
  homebrew:
    name: node
    update_homebrew: yes
    state: present

- name: Install watchman
  homebrew:
    name: watchman
    state: present

- name: Install react-native CLI
  npm:
    name: react-native
    global: yes
